In [6]:
# List vs Arrays

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L :
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [7]:
L.append(4)

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
L = L + [5]

In [11]:
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
L2 = []

In [13]:
for e in L:
    L2.append(e+e)

In [14]:
L2

[2, 4, 6, 8, 10]

In [15]:
A + A

array([2, 4, 6])

In [16]:
# Scalar multiplication
2 * A

array([2, 4, 6])

In [17]:
2 *L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
A**2

array([1, 4, 9], dtype=int32)

In [20]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [21]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [22]:
# Go to slide

In [23]:
a = np.array([1,2])

In [24]:
b = np.array([2,1])

In [25]:
dot = 0

In [26]:
for e, f in zip(a,b):
    dot +=e*f

In [27]:
dot

4

In [28]:
a*b

array([2, 2])

In [29]:
np.sum(a*b)

4

In [30]:
np.dot(a,b)

4